# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IslamicAudioBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IslamicAudioBook
  pod 'Alamofire'
  pod 'Signals'
  pod 'SDWebImage'
  pod 'RappleProgressHUD'
  pod 'Siren' # Swift 5.1+
  pod 'RealmSwift'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['ENABLE_BITCODE'] = 'NO'
          end
      end
  end


end
